### ISSUE TITLE
Pushing out the arm64 images to docker hub?

### ISSUE THREAD

**Issue by deitch** [projectcalico/go-build#22]
Are there plans to push out the alternate architecture images to the hub? The `Makefile` says that the image names are:

* `calico/go-build`: x86_64
* `calico/go-build-arm64`: arm64

However, the hub only has the `calico/go-build` (x86_64) image. 

Will you be doing one of:

* Pushing `calico/go-build-arm64` out?
* Creating a single multi-arch `calico/go-build` with a multi-arch manifest?

The `docker manifest` subcommand hasn't been merged in yet (see [this](https://github.com/docker/cli/pull/138) ), but you can use the `manifest-tool` to do the same thing.

**Comment by deitch** [comment]
See [PR](https://github.com/projectcalico/go-build/pull/23)

**Comment by djlwilder** [comment]
I am also working to add alternate architecture support in Calico,  ppc64le in my case.

Adding support for the milti-architecture image manifests definitely needed.  However, putting the infrastructure in-place to enable the community to build and support these architectures may be a harder problem to solve.  How can we work to solve this?   
How can I help contribute to the solution?  Is this an appropriate venue for this discussion?

@deitch
@liljenstolpe
@caseydavenport

**Comment by liljenstolpe** [comment]
Is anyone here aware of a way to get CircleCI to support ARM or PPC?  If not, does anyone know a CI pipeline that does support either/both?  In worse case, does anyone know a cloud provider of PPC and ARM CPU's (I know about Packet.net's ARM support)?

**Comment by deitch** [comment]
> I am also working to add alternate architecture support in Calico, ppc64le in my case

Great. Happy to work with you @djlwilder, but I believe we both depend on the good team here at Calico/Tigera. I am working only on arm64 and x86_64, but I tried to make any of the PRs I have done (3 so far, more will come once those are in) generic, especially since much of the build toolset referenced ppc64ie. I will cc you on those PRs, see if I made any errors that cause issues for ppc64ie?

> Adding support for the milti-architecture image manifests definitely needed

100%. I do a lot of work with LinuxKit, we use multi-arch manifests there exclusively. 

I would like to request that we first get them working on multiple architectures, then multi-arch manifests, in a 2 stage process? I am concerned that if we do it all at once, it will hold things up?

> putting the infrastructure in-place to enable the community to build and support these architectures

It is. To the best of my knowledge, no CI-as-a-service (is that a real term?) supports anything other than x86_64. However, I have heard reports that a number of them are working towards getting arm64 in place (probably through packet, since they are the only arm64 cloud provider out there to the best of my knowledge). 

> Is anyone here aware of a way to get CircleCI to support ARM or PPC?

@liljenstolpe , do you have any connections to CircleCI? Or just using them a bit as a customer? We both know the Packet team pretty well, I am sure they would be happy to have a conversation.

**Comment by liljenstolpe** [comment]
No, I don't unfortunately.

**Comment by djlwilder** [comment]
@liljenstolpe IBM had provided other open source projects with ppc VMs for Ci.  That might be an option for Calico.  However, I don't believe CircleCi has a ppc port, Jenkins is typically used in these cases. Would Calico consider switching to Jenkins?  Although this wont solve the issue with arm64.

**Comment by deitch** [comment]
>  I don't believe CircleCi has a ppc port

They don't have arm64 either, unfortunately. No one does. I think it would be a competitive advantage in an increasingly tight CIaaS space. 

> Would Calico consider switching to Jenkins?

The challenge with Jenkins is you have to run it and manage it. That is why Circle/Travis/etc. are so popular. Who wants to manage (and pay to keep up all the time) a bunch of VMs?

**Comment by hazzim** [comment]
I can help to manage and maintain a Jenkins server (if you get some kind of sponsorship for one), I have 3 years of experience, and I'm in Mexico, so my help could be in Central time most of the time.

**Comment by deitch** [comment]
> I can help to manage and maintain a Jenkins server (if you get some kind of sponsorship for one)

It is a pity, though. I doubt Tigera pays anything for CI, since most CIaaS are free for open source projects... but no CI (yet) supports anything other than `x86_64`.

**Comment by ahrkrak** [comment]
Interesting idea here to run ARM CI using QEMU... https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html

**Comment by deitch** [comment]
It is an interesting idea, if painfully slow. But better than nothing?

**Comment by liljenstolpe** [comment]
Here's a more current version of what @ahrkrak mentioned: https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/

**Comment by deitch** [comment]
Got to be slow, but better than not having it.

So where do we want to take it from here?

**Comment by liljenstolpe** [comment]
We need to talk internally.
