### ISSUE TITLE
go-build build is failing, glibc is the problem.

### ISSUE THREAD

**Issue by djlwilder** [projectcalico/go-build#29]
Docker build of the go-build images are (all architectures) started failing today.  This is the error.
<....>
 ---> Running in 7ae02d7469e8
The command '/bin/sh -c wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub' returned a non-zero code: 5
Makefile:37: recipe for target 'calico/go-build' failed

It can be fixed by updating the url to:
https://cdn.rawgit.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub
 ( as recommended on https://rawgit.com/)

However,  why do we need glibc in the first place, alpine is based libc.musl?    I discovered that we have been installing this same package for all arch,  yet the lib installed in all cases is for x86-64 so it could not be working on anything except the amd image.  Therefore it must not be needed.

I suggest we remove the glibc from all the Dockerfiles. 

@fasaxc   WDYT

**Comment by fasaxc** [comment]
@djlwilder glibc is not used in Calico but it is used for other builds that Tigera do, which is a bit messy.  I'd prefer if we had a separate build container for those builds but I think I'll get pushback if I suggest that.  AFAIC, you can leave glibc out of the non-amd64 containers and leave it to the Tigera team to maintain that fragment.

**Comment by djlwilder** [comment]
Resolved in PR 33.  Thanks.
