### ISSUE TITLE
why not upgrade to golang:1.19.5 for all platforms?

### ISSUE THREAD

**Issue by yanggangtony** [projectcalico/go-build#417]
the pr [1.19.5 just update amd64](https://github.com/projectcalico/go-build/pull/414).
why not update all others?
like 
```
Dockerfile.s390x,
Dockerfile.ppc64le,
Dockerfile.armv7,
Dockerfile.arm64
```

**Comment by mazdakn** [comment]
@frozenprocess is there something stopping the upgrade to `go1.19.5` for other architectures?

**Comment by frozenprocess** [comment]
@mazdakn nothing that I know of.

@yanggangtony, if you create a PR for it, I'll be happy to review and merge it! :incoming_envelope:

**Comment by yanggangtony** [comment]
/assign
@frozenprocess @mazdakn 
thanks for response..
I will do it later.
