### ISSUE TITLE
Replace manifest-tool with `docker manifest` command

### ISSUE THREAD

**Issue by tomdee** [projectcalico/go-build#55]
It's still experimental, but only required when releasing `go-build`. Still probably preferable to grabbing the tool from estep's github.

**Comment by mkumatag** [comment]
there were few issues in `docker manifest` command pushing manifest with proper image size, you can refer https://github.com/docker/cli/pull/1156 for more information. Time being lets us stick to manifest-tool only.

In future once it becomes stable we can change.

**Comment by tomdee** [comment]
Thanks for the info, sounds like it's worth sticking with manifest-tool
