### ISSUE TITLE
s390x Dockerfile needs base image updated

### ISSUE THREAD

**Issue by lmm** [projectcalico/go-build#74]
Most of our Dockerfiles have migrated over to Alpine v3.9 and Go 1.12 but s390x is still using `s390x/golang:1.11.9-alpine3.8`, which means the image is missing some security patches (e.g. [this](https://groups.google.com/forum/#!topic/golang-nuts/fCQWxqxP8aA) most recent one).

Any s390x users want to take this on? 😄

**Comment by frozenprocess** [comment]
Fixed in #418
